//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Resources/PlayerAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerAction"",
    ""maps"": [
        {
            ""name"": ""UnitControl"",
            ""id"": ""a1962998-4dc0-45b0-817c-243dbd891d4a"",
            ""actions"": [
                {
                    ""name"": ""Select Unit"",
                    ""type"": ""Button"",
                    ""id"": ""d20880e3-e99c-4702-af0a-82956c17c502"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Multi Select With Shift"",
                    ""type"": ""Button"",
                    ""id"": ""2d05f745-6188-4ca4-9d34-477b6b270a6b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Multi Select With Mouse"",
                    ""type"": ""Value"",
                    ""id"": ""fd5083a2-9809-405f-b610-1ccd3df77297"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RePlayTest"",
                    ""type"": ""Button"",
                    ""id"": ""8f7266a6-8274-4d4e-b628-4c5948fe3e98"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d9c035ec-8939-403a-aaf0-a0fc5ebb8873"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": ""KeyBoardAndMouse"",
                    ""action"": ""Select Unit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3f6bf30-5ab0-43d3-b66c-049428518aef"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyBoardAndMouse"",
                    ""action"": ""Multi Select With Shift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da2a4fd7-3e44-4a92-9604-cbe4976c7838"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": "";KeyBoardAndMouse"",
                    ""action"": ""Multi Select With Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73774489-f4d2-43fe-ae9f-b63d357f5082"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RePlayTest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Building"",
            ""id"": ""66d63649-36c1-4c68-ae40-e47fc6466e4c"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""180613c3-93fd-4a7c-9273-2ab03203102a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3aa774cd-fb01-4c89-9beb-3a0dd6b34235"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyBoardAndMouse"",
            ""bindingGroup"": ""KeyBoardAndMouse"",
            ""devices"": []
        }
    ]
}");
        // UnitControl
        m_UnitControl = asset.FindActionMap("UnitControl", throwIfNotFound: true);
        m_UnitControl_SelectUnit = m_UnitControl.FindAction("Select Unit", throwIfNotFound: true);
        m_UnitControl_MultiSelectWithShift = m_UnitControl.FindAction("Multi Select With Shift", throwIfNotFound: true);
        m_UnitControl_MultiSelectWithMouse = m_UnitControl.FindAction("Multi Select With Mouse", throwIfNotFound: true);
        m_UnitControl_RePlayTest = m_UnitControl.FindAction("RePlayTest", throwIfNotFound: true);
        // Building
        m_Building = asset.FindActionMap("Building", throwIfNotFound: true);
        m_Building_Newaction = m_Building.FindAction("New action", throwIfNotFound: true);
    }

    ~@PlayerAction()
    {
        UnityEngine.Debug.Assert(!m_UnitControl.enabled, "This will cause a leak and performance issues, PlayerAction.UnitControl.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Building.enabled, "This will cause a leak and performance issues, PlayerAction.Building.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UnitControl
    private readonly InputActionMap m_UnitControl;
    private List<IUnitControlActions> m_UnitControlActionsCallbackInterfaces = new List<IUnitControlActions>();
    private readonly InputAction m_UnitControl_SelectUnit;
    private readonly InputAction m_UnitControl_MultiSelectWithShift;
    private readonly InputAction m_UnitControl_MultiSelectWithMouse;
    private readonly InputAction m_UnitControl_RePlayTest;
    public struct UnitControlActions
    {
        private @PlayerAction m_Wrapper;
        public UnitControlActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectUnit => m_Wrapper.m_UnitControl_SelectUnit;
        public InputAction @MultiSelectWithShift => m_Wrapper.m_UnitControl_MultiSelectWithShift;
        public InputAction @MultiSelectWithMouse => m_Wrapper.m_UnitControl_MultiSelectWithMouse;
        public InputAction @RePlayTest => m_Wrapper.m_UnitControl_RePlayTest;
        public InputActionMap Get() { return m_Wrapper.m_UnitControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UnitControlActions set) { return set.Get(); }
        public void AddCallbacks(IUnitControlActions instance)
        {
            if (instance == null || m_Wrapper.m_UnitControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UnitControlActionsCallbackInterfaces.Add(instance);
            @SelectUnit.started += instance.OnSelectUnit;
            @SelectUnit.performed += instance.OnSelectUnit;
            @SelectUnit.canceled += instance.OnSelectUnit;
            @MultiSelectWithShift.started += instance.OnMultiSelectWithShift;
            @MultiSelectWithShift.performed += instance.OnMultiSelectWithShift;
            @MultiSelectWithShift.canceled += instance.OnMultiSelectWithShift;
            @MultiSelectWithMouse.started += instance.OnMultiSelectWithMouse;
            @MultiSelectWithMouse.performed += instance.OnMultiSelectWithMouse;
            @MultiSelectWithMouse.canceled += instance.OnMultiSelectWithMouse;
            @RePlayTest.started += instance.OnRePlayTest;
            @RePlayTest.performed += instance.OnRePlayTest;
            @RePlayTest.canceled += instance.OnRePlayTest;
        }

        private void UnregisterCallbacks(IUnitControlActions instance)
        {
            @SelectUnit.started -= instance.OnSelectUnit;
            @SelectUnit.performed -= instance.OnSelectUnit;
            @SelectUnit.canceled -= instance.OnSelectUnit;
            @MultiSelectWithShift.started -= instance.OnMultiSelectWithShift;
            @MultiSelectWithShift.performed -= instance.OnMultiSelectWithShift;
            @MultiSelectWithShift.canceled -= instance.OnMultiSelectWithShift;
            @MultiSelectWithMouse.started -= instance.OnMultiSelectWithMouse;
            @MultiSelectWithMouse.performed -= instance.OnMultiSelectWithMouse;
            @MultiSelectWithMouse.canceled -= instance.OnMultiSelectWithMouse;
            @RePlayTest.started -= instance.OnRePlayTest;
            @RePlayTest.performed -= instance.OnRePlayTest;
            @RePlayTest.canceled -= instance.OnRePlayTest;
        }

        public void RemoveCallbacks(IUnitControlActions instance)
        {
            if (m_Wrapper.m_UnitControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUnitControlActions instance)
        {
            foreach (var item in m_Wrapper.m_UnitControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UnitControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UnitControlActions @UnitControl => new UnitControlActions(this);

    // Building
    private readonly InputActionMap m_Building;
    private List<IBuildingActions> m_BuildingActionsCallbackInterfaces = new List<IBuildingActions>();
    private readonly InputAction m_Building_Newaction;
    public struct BuildingActions
    {
        private @PlayerAction m_Wrapper;
        public BuildingActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Building_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Building; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BuildingActions set) { return set.Get(); }
        public void AddCallbacks(IBuildingActions instance)
        {
            if (instance == null || m_Wrapper.m_BuildingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BuildingActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(IBuildingActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(IBuildingActions instance)
        {
            if (m_Wrapper.m_BuildingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBuildingActions instance)
        {
            foreach (var item in m_Wrapper.m_BuildingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BuildingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BuildingActions @Building => new BuildingActions(this);
    private int m_KeyBoardAndMouseSchemeIndex = -1;
    public InputControlScheme KeyBoardAndMouseScheme
    {
        get
        {
            if (m_KeyBoardAndMouseSchemeIndex == -1) m_KeyBoardAndMouseSchemeIndex = asset.FindControlSchemeIndex("KeyBoardAndMouse");
            return asset.controlSchemes[m_KeyBoardAndMouseSchemeIndex];
        }
    }
    public interface IUnitControlActions
    {
        void OnSelectUnit(InputAction.CallbackContext context);
        void OnMultiSelectWithShift(InputAction.CallbackContext context);
        void OnMultiSelectWithMouse(InputAction.CallbackContext context);
        void OnRePlayTest(InputAction.CallbackContext context);
    }
    public interface IBuildingActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
